DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS OPERATION;

CREATE TABLE ACCOUNT (
	ACCOUNT_NUMBER INT PRIMARY KEY,
	ACCOUNT_TYPE VARCHAR(100) NOT NULL,
	INITIAL_BALANCE BIGINT NOT NULL,
	STATE BOOLEAN DEFAULT TRUE NOT NULL,
	CLIENT_ID INTEGER NOT NULL
);

CREATE TABLE OPERATION (
	OPERATION_ID INT AUTO_INCREMENT PRIMARY KEY,
	OPERATION_DATE DATE NOT NULL,
	OPERATION_TYPE VARCHAR(100) NOT NULL,
    OPERATION_VALUE BIGINT NOT NULL,
    NEW_BALANCE BIGINT NOT NULL,
    ACCOUNT INTEGER NOT NULL,
	CONSTRAINT FK_CLIENT_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNT(ACCOUNT_NUMBER)
);

INSERT INTO ACCOUNT (ACCOUNT_NUMBER, ACCOUNT_TYPE, INITIAL_BALANCE, STATE, CLIENT_ID) VALUES (585545, 'Corriente', 1000, 1, 976431);
INSERT INTO OPERATION (OPERATION_DATE, OPERATION_TYPE, OPERATION_VALUE, NEW_BALANCE, ACCOUNT) VALUES ('2022-02-10', 'Deposito', 600, 1600, 585545);